;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	electric-pair-delete-pair
	kill-region
	mwim-beginning
	mwim-end
	org-self-insert-command
	sp-forward-sexp
	))

(setq mc/cmds-to-run-once
      '(
	dap-tooltip-mouse-motion
	))
